version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - codecov/upload:
                file: coverage/coverage-final.json
            - run: yarn install
            - run: yarn codecov
workflows:
  build-and-test:
    jobs:
      - build-and-test
